global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape the Django Backend
  - job_name: 'django_backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']